name: Challenge1
on: workflow_dispatch

jobs: 
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: print date
      run: date

    - name: print working directory
      run: pwd

    - name: print contents
      run: ls -a
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: check python version
      run: python --version

    - name: set up pandas
      run: python -m pip install pandas

    - name: create artefact
      run: echo "# This is my python artefact" > artifact.py
    
    - name: run the python file
      run: python3 artifact.py